# Generated by Django 6.0 on 2025-12-09 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('master_answer', models.TextField()),
                ('keywords', models.TextField(help_text='Comma-separated mandatory keywords')),
                ('max_marks', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('answer_sheet_image', models.ImageField(upload_to='answer_sheets/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.keyanswer')),
            ],
        ),
    ]
